### ISSUE TITLE
Documentation update, code standardization and refactoring

### ISSUE THREAD

**Issue by mexanick** [yrenier/cta-lstchain#10]
**Adherence to PEP8 standards**
Please add docstrings to each method (including abstract ones), place two empty lines before each method declaration,
remove extra empty lines between the method docstring and method body, between `if` condition and operator block, etc.
Also, please use the same code constructions for numpy array extensions (either `a[..., None]` or `a[..., np.newaxis]`)

**Required Documentation Updates**

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L51-L52
Specify the parameter set

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L53-L55
Photon instead of photoelectron? Also need to specify array's shape

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L56-L59
Can't `is_high_gain` be deduced from the `gain` array?

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L74-L75
Specify the parameter set

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L148
Missing docstring and extra empty line

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L474-L477
This docstring is good for abstract method, but here we need to have an actual description of what and how the method is doing

**Code refactoring**
https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L511-L516
I'm not sure I understand what's happening here with `mask` and `self.photo_peaks`. At the end, you transform range (0,1,2...N) to (1,1,2...N) and the mask is (1,0,0...). Then, at l.519 you convert `self.photo_peaks` back. Is it all just to avoid `log(0)`? In this case, much easier to use the array slicing and ditch the first element (anyway, `log(1)=0`)

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L569-L577
1. Use enumerate
2. Explain the hardcoded numbers and their origin. Refactor if needed

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L596
Why is this required?

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L601
Something more descriptive then `x` is desired

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L658-L681
Looks like your gaussian approximation is only used for logging, but is actually never returned. Also please adhere to PEP8 in naming convention (names should be descriptive!)

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L714
Bad name of the method

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L846
Bad name of the method

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L852-L856
To be removed?

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L936-L997
Remove

https://github.com/cta-sst-1m/cta-lstchain/blob/929645eacc18d590bfc576f14d8a2f1c76ccb0ac/lstchain/reco/reconstructor.py#L1005-L1015
To be removed?

**Comment by gabemery** [comment]
Hi, a few comments on unsolved questions :

- place two empty lines before each method declaration
In PEP8 I see it is 1 empty line for method in classes.

- Can't `is_high_gain` be deduced from the `gain` array?
The gain here is corrected for the flat field. So it is not the input gain anymore. Assuming that the effect is limited and the high and low gain well separated it should be possible to deduce is_high_gain by cutting at the middle point between each gain but it feels wrong to do so.

- Something more descriptive then x is desired
Not sure of what an explicit name for mu+crosstalk would be.

Everything else is either already corrected or will be soon.

**Comment by mexanick** [comment]
> Hi, a few comments on unsolved questions :
> 
> > * place two empty lines before each method declaration
>   In PEP8 I see it is 1 empty line for method in classes.

Yes, I meant the methods outside of class

> > * Can't `is_high_gain` be deduced from the `gain` array?

>   The gain here is corrected for the flat field. So it is not the input gain anymore. Assuming that the effect is limited and the high and low gain well separated it should be possible to deduce is_high_gain by cutting at the middle point between each gain but it feels wrong to do so.

True, HG is about 20% higher then low gain, might be a bit difficult to separate

> > * Something more descriptive then x is desired

>   Not sure of what an explicit name for mu+crosstalk would be.

E.g. `signal_strength_with_crosstalk`. From [PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names):
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
>
> Variable names follow the same convention as function names.
